/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.Interfaces;
import es.medac.ProyectoInterfaces.Informe_Empleado;
import java.io.FileWriter;
import java.io.BufferedWriter;      
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Informe_Empleados extends javax.swing.JFrame {
  
  Informe_Empleado informe =new Informe_Empleado(0, null);
  
    public Informe_Empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        Nombre = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        Apellidos = new javax.swing.JTextField();
        a1 = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        a2 = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        a3 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        a4 = new javax.swing.JLabel();
        Anos_exp = new javax.swing.JTextField();
        a5 = new javax.swing.JLabel();
        H_trabajadas = new javax.swing.JTextField();
        a6 = new javax.swing.JLabel();
        Pago_hora = new javax.swing.JTextField();
        a7 = new javax.swing.JLabel();
        Numero_Hijos = new javax.swing.JTextField();
        a8 = new javax.swing.JLabel();
        hacienda = new javax.swing.JRadioButton();
        retencion = new javax.swing.JRadioButton();
        a9 = new javax.swing.JLabel();
        Estudios1 = new javax.swing.JComboBox<>();
        Estudios = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        procesar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Texto_Ubi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, -1));

        a.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a.setForeground(new java.awt.Color(255, 255, 255));
        a.setText("Nombre");
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, -1));

        a1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setText("Apellidos");
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIActionPerformed(evt);
            }
        });
        getContentPane().add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, -1));

        a2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 255, 255));
        a2.setText("DNI");
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, -1));

        a3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 255, 255));
        a3.setText("Dirección");
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        Edad.setToolTipText("          ");
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });
        getContentPane().add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, -1));

        a4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a4.setForeground(new java.awt.Color(255, 255, 255));
        a4.setText("Edad");
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Anos_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anos_expActionPerformed(evt);
            }
        });
        getContentPane().add(Anos_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 70, -1));

        a5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a5.setForeground(new java.awt.Color(255, 255, 255));
        a5.setText("Años Experiencia");
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 140, -1));

        H_trabajadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_trabajadasActionPerformed(evt);
            }
        });
        getContentPane().add(H_trabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 70, -1));

        a6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a6.setForeground(new java.awt.Color(255, 255, 255));
        a6.setText("Horas de trabajo");
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, 20));

        Pago_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pago_horaActionPerformed(evt);
            }
        });
        getContentPane().add(Pago_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 70, -1));

        a7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a7.setForeground(new java.awt.Color(255, 255, 255));
        a7.setText("Pago por hora");
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        Numero_Hijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_HijosActionPerformed(evt);
            }
        });
        getContentPane().add(Numero_Hijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 70, -1));

        a8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a8.setForeground(new java.awt.Color(255, 255, 255));
        a8.setText("Numero hijos");
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        Botones.add(hacienda);
        hacienda.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        hacienda.setForeground(new java.awt.Color(255, 255, 255));
        hacienda.setText("Hacienda 1.5%");
        hacienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haciendaActionPerformed(evt);
            }
        });
        getContentPane().add(hacienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        Botones.add(retencion);
        retencion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        retencion.setForeground(new java.awt.Color(255, 255, 255));
        retencion.setSelected(true);
        retencion.setText("Retencion 2.5%");
        retencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retencionActionPerformed(evt);
            }
        });
        getContentPane().add(retencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        a9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        a9.setForeground(new java.awt.Color(255, 255, 255));
        a9.setText("Pensión");
        getContentPane().add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        Estudios1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Universidad", "Bachillerato", "ESO" }));
        Estudios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estudios1ActionPerformed(evt);
            }
        });
        getContentPane().add(Estudios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        Estudios.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Estudios.setForeground(new java.awt.Color(255, 255, 255));
        Estudios.setText("Estudios");
        getContentPane().add(Estudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        Guardar.setBackground(new java.awt.Color(0, 0, 51));
        Guardar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 100, 60));

        procesar.setBackground(new java.awt.Color(0, 0, 51));
        procesar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        procesar.setForeground(new java.awt.Color(255, 255, 255));
        procesar.setText("Procesar");
        procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarActionPerformed(evt);
            }
        });
        getContentPane().add(procesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 100, 50));

        Limpiar.setBackground(new java.awt.Color(0, 0, 51));
        Limpiar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 100, 50));

        Salir.setBackground(new java.awt.Color(255, 0, 51));
        Salir.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 100, 60));

        Texto_Ubi.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Texto_Ubi.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Ubi.setText("Informe Empleado");
        getContentPane().add(Texto_Ubi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Resultado.setBackground(new java.awt.Color(0, 51, 51));
        Resultado.setColumns(20);
        Resultado.setForeground(new java.awt.Color(255, 255, 255));
        Resultado.setRows(5);
        jScrollPane1.setViewportView(Resultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 490, 240));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/Interfaces/verde.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 940, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosActionPerformed
        
    }//GEN-LAST:event_ApellidosActionPerformed

    private void DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIActionPerformed
        
    }//GEN-LAST:event_DNIActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed

    }//GEN-LAST:event_EdadActionPerformed

    private void Numero_HijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_HijosActionPerformed

    }//GEN-LAST:event_Numero_HijosActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
            
    }//GEN-LAST:event_NombreActionPerformed

    private void procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarActionPerformed
        Resultado.setText(Informe_final());
    }//GEN-LAST:event_procesarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        Salida_sin_guardar();
        this.setVisible(false);
        Informe_Empleados p = new Informe_Empleados();
        p.setVisible(true);
    }//GEN-LAST:event_LimpiarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Salida_sin_guardar();
        System.exit(WIDTH);
    }//GEN-LAST:event_SalirActionPerformed

    private void retencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retencionActionPerformed
        
    }//GEN-LAST:event_retencionActionPerformed

    private void haciendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haciendaActionPerformed
       
    }//GEN-LAST:event_haciendaActionPerformed

    private void H_trabajadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_trabajadasActionPerformed
      
    }//GEN-LAST:event_H_trabajadasActionPerformed

    private void Estudios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estudios1ActionPerformed

    }//GEN-LAST:event_Estudios1ActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
       
    }//GEN-LAST:event_DireccionActionPerformed

    private void Anos_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anos_expActionPerformed
        
    }//GEN-LAST:event_Anos_expActionPerformed

    private void Pago_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pago_horaActionPerformed
       
    }//GEN-LAST:event_Pago_horaActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
    Guardado_Archivo();
    }//GEN-LAST:event_GuardarActionPerformed
  int numArchivotxt=0; 
  int numError=0; 
    public String Informe_final(){
     try {
        numError=0;
        if(retencion.isSelected()){
           String pension = "rentencion 2.5%";
           informe.setRetencion(pension);
       }else if(hacienda.isSelected()){
            String pension = "hacienda 1.5%";
           informe.setHacienda(pension);              
       }
        Informe_Empleado informe =new Informe_Empleado(
            Integer.parseInt(Numero_Hijos.getText()), 
            hacienda.getText(),
            retencion.getText(),
            Nombre.getText(),
            Apellidos.getText(),
            DNI.getText(),
            Direccion.getText(),
            Integer.parseInt(Edad.getText()),
            Estudios1.getSelectedItem().toString(),
            Integer.parseInt(Anos_exp.getText()),
            Integer.parseInt(H_trabajadas.getText()),
            Integer.parseInt(Pago_hora.getText())    
        );
        String Informe_final=informe.imprimirReciboPago();
        return Informe_final;
        
         } catch (NumberFormatException e) {
             numError++; 
        JOptionPane.showMessageDialog(this, 
                "Error, pusiste una variable de texto en:" + "\n" +
                "-Edad" + "\n" +
                "-Años de Esxperiencia" + "\n" +
                "-Horas trabajadas"+"\n" +
                "-Pago por hora"+"\n" +
                "-Numero de hijos"+"\n" +
                "También es posible que no rellenases alguna de las casillas, ten cuidado", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        numArchivotxt=0;
        return null; 
    }
    }
    public void Guardado_Archivo(){
        numArchivotxt++;
        String contenido = Informe_final();
        if(numError==0){
        String rutaArchivo="";
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setSelectedFile(new File("Informe_de_"+Nombre.getText()+"_"+numArchivotxt+".txt"));
                fileChooser.setDialogTitle("Selecciona un fichero");
                int resultado = fileChooser.showSaveDialog(null);
                if (resultado == JFileChooser.APPROVE_OPTION){
                rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();
            }
        try{
            FileWriter archivoEscritura = new FileWriter(rutaArchivo);
            BufferedWriter bufferEscritura = new BufferedWriter(archivoEscritura);

            bufferEscritura.write(contenido);
            bufferEscritura.close();
            archivoEscritura.close();
            JOptionPane.showMessageDialog(this, "Informe guardado");
            
        }catch (IOException e) {
            numArchivotxt=0;
            JOptionPane.showMessageDialog(this, "Error al crear el archivo", "Error",JOptionPane.ERROR_MESSAGE);
        }
        }
 }
    
     public void Salida_sin_guardar(){
                  if(numArchivotxt==0){
            Object[] opciones = {"Si", "No"};
            int respuesta = JOptionPane.showOptionDialog(this,
            "¿Deseas salir sin guardar?",
            "Pregunta",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]);
            
                if (respuesta != 0){
                Guardado_Archivo();  
                }       
    }
    
}
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informe_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informe_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informe_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informe_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informe_Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Anos_exp;
    private javax.swing.JTextField Apellidos;
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JTextField DNI;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Edad;
    private javax.swing.JLabel Estudios;
    private javax.swing.JComboBox<String> Estudios1;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField H_trabajadas;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Numero_Hijos;
    private javax.swing.JTextField Pago_hora;
    private javax.swing.JTextArea Resultado;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Texto_Ubi;
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.JLabel fondo;
    private javax.swing.JRadioButton hacienda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton procesar;
    private javax.swing.JRadioButton retencion;
    // End of variables declaration//GEN-END:variables
}
