/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.Interfaces;

/**
 *
 * @author Usuario
 */
public class Interfaces extends javax.swing.JFrame {

    /**
     * Creates new form Interfaces
     */
    public Interfaces() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartel = new javax.swing.JLabel();
        Informe = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Recibo = new javax.swing.JButton();
        Fondo_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartel.setBackground(new java.awt.Color(51, 0, 102));
        cartel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cartel.setText("Menu Principal");
        getContentPane().add(cartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 200, 130));

        Informe.setBackground(new java.awt.Color(102, 102, 255));
        Informe.setForeground(new java.awt.Color(255, 255, 255));
        Informe.setText("Informe");
        Informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeActionPerformed(evt);
            }
        });
        getContentPane().add(Informe, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 120, 50));

        Salir.setBackground(new java.awt.Color(255, 0, 51));
        Salir.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 120, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/Interfaces/fondo2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 230, 90));

        Recibo.setBackground(new java.awt.Color(51, 51, 255));
        Recibo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Recibo.setForeground(new java.awt.Color(255, 255, 255));
        Recibo.setText("Recibo");
        Recibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReciboActionPerformed(evt);
            }
        });
        getContentPane().add(Recibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 120, 50));

        Fondo_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/Interfaces/medac.jpg"))); // NOI18N
        getContentPane().add(Fondo_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -20, 1020, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeActionPerformed
        this.setVisible(false);//te lleva a Informe_Empleados
        Informe_Empleados p = new Informe_Empleados();
        p.setVisible(true);
    }//GEN-LAST:event_InformeActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(WIDTH);//cierra el programa
    }//GEN-LAST:event_SalirActionPerformed

    private void ReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReciboActionPerformed
        this.setVisible(false);//te lleva a Recibo_Empleado
            Recibo_Empleados p = new Recibo_Empleados();
        p.setVisible(true);
    }//GEN-LAST:event_ReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo_1;
    private javax.swing.JButton Informe;
    private javax.swing.JButton Recibo;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel cartel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
