/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.Interfaces;
import es.medac.ProyectoInterfaces.Empleado_Recibo;
import java.io.FileWriter;             
import java.io.BufferedWriter;                                                        
import java.io.File;                   
import java.io.IOException;             
import javax.swing.JFileChooser;        
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Recibo_Empleados extends javax.swing.JFrame {
  
    
    public Recibo_Empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        fondo = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        Apellidos = new javax.swing.JTextField();
        a1 = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        a2 = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        a3 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        a4 = new javax.swing.JLabel();
        Anos_exp = new javax.swing.JTextField();
        a5 = new javax.swing.JLabel();
        H_trabajadas = new javax.swing.JTextField();
        a6 = new javax.swing.JLabel();
        Pago_hora = new javax.swing.JTextField();
        a7 = new javax.swing.JLabel();
        Estudios1 = new javax.swing.JComboBox<>();
        Estudios = new javax.swing.JLabel();
        Meses = new javax.swing.JComboBox<>();
        a8 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        procesar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Texto_Ubi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/Interfaces/fondo2.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 60, 20));

        a.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        a.setForeground(new java.awt.Color(255, 255, 255));
        a.setText("Nombre");
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 50, -1));

        Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, 20));

        a1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setText("Apellidos");
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIActionPerformed(evt);
            }
        });
        getContentPane().add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 60, 20));

        a2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 255, 255));
        a2.setText("DNI");
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 60, 20));

        a3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 255, 255));
        a3.setText("Dirección");
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        Edad.setToolTipText("          ");
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });
        getContentPane().add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 60, 20));

        a4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        a4.setForeground(new java.awt.Color(255, 255, 255));
        a4.setText("Edad");
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        Anos_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anos_expActionPerformed(evt);
            }
        });
        getContentPane().add(Anos_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 70, -1));

        a5.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        a5.setForeground(new java.awt.Color(255, 255, 255));
        a5.setText("Años Experiencia");
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, -1));

        H_trabajadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_trabajadasActionPerformed(evt);
            }
        });
        getContentPane().add(H_trabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 70, -1));

        a6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        a6.setForeground(new java.awt.Color(255, 255, 255));
        a6.setText("Horas trabajadas");
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, 20));

        Pago_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pago_horaActionPerformed(evt);
            }
        });
        getContentPane().add(Pago_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 70, -1));

        a7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        a7.setForeground(new java.awt.Color(255, 255, 255));
        a7.setText("Pago por hora");
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        Estudios1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Universidad", "Bachillerato", "ESO" }));
        Estudios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estudios1ActionPerformed(evt);
            }
        });
        getContentPane().add(Estudios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        Estudios.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Estudios.setForeground(new java.awt.Color(255, 255, 255));
        Estudios.setText("Estudios");
        getContentPane().add(Estudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        Meses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        Meses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesesActionPerformed(evt);
            }
        });
        getContentPane().add(Meses, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 100, -1));

        a8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        a8.setForeground(new java.awt.Color(255, 255, 255));
        a8.setText("Recibo");
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        Guardar.setBackground(new java.awt.Color(0, 0, 51));
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 160, 70));

        procesar.setBackground(new java.awt.Color(0, 0, 51));
        procesar.setForeground(new java.awt.Color(255, 255, 255));
        procesar.setText("Procesar");
        procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarActionPerformed(evt);
            }
        });
        getContentPane().add(procesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 160, 70));

        Limpiar.setBackground(new java.awt.Color(0, 0, 51));
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 160, 60));

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 120, 70));

        Texto_Ubi.setBackground(new java.awt.Color(0, 0, 0));
        Texto_Ubi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Texto_Ubi.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Ubi.setText("Empleado Recibo:");
        getContentPane().add(Texto_Ubi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        resultado.setBackground(new java.awt.Color(0, 0, 51));
        resultado.setColumns(20);
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 490, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/Interfaces/verde.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -230, 2360, 1460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosActionPerformed
        
    }//GEN-LAST:event_ApellidosActionPerformed

    private void DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIActionPerformed
       
    }//GEN-LAST:event_DNIActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
      
    }//GEN-LAST:event_EdadActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
            
    }//GEN-LAST:event_NombreActionPerformed

    private void procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarActionPerformed
         resultado.setText(Recibo_final());
    }//GEN-LAST:event_procesarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        Salida_sin_guardar();
        this.setVisible(false);
        Recibo_Empleados p = new Recibo_Empleados();
        p.setVisible(true);
    }//GEN-LAST:event_LimpiarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
    Salida_sin_guardar();
    System.exit(WIDTH);
    }//GEN-LAST:event_SalirActionPerformed

    private void H_trabajadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_trabajadasActionPerformed
       
    }//GEN-LAST:event_H_trabajadasActionPerformed

    private void Estudios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estudios1ActionPerformed
    
    }//GEN-LAST:event_Estudios1ActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
      
    }//GEN-LAST:event_DireccionActionPerformed

    private void Anos_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anos_expActionPerformed
        
    }//GEN-LAST:event_Anos_expActionPerformed

    private void Pago_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pago_horaActionPerformed
        
    }//GEN-LAST:event_Pago_horaActionPerformed

    private void MesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesesActionPerformed
       
    }//GEN-LAST:event_MesesActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
             Guardado_Archivo();     
    }//GEN-LAST:event_GuardarActionPerformed
    
    int numArchivotxt=0;
    int numError=0;
    public String Recibo_final(){
       try{
        numError=0;
        Empleado_Recibo recibo =new Empleado_Recibo( 
        (String) Meses.getSelectedItem(),
        Nombre.getText(),
        Apellidos.getText(),
        DNI.getText(),
        Direccion.getText(), 
        Integer.parseInt(Edad.getText()),
        Estudios1.getSelectedItem().toString(),
        Integer.parseInt(Anos_exp.getText()),
        Integer.parseInt(H_trabajadas.getText()),
        Integer.parseInt(Pago_hora.getText())    
        );
        String Recibo_final=recibo.imprimirReciboPago();
        return Recibo_final;
        } catch (NumberFormatException e) {
        numError++;
        JOptionPane.showMessageDialog(this, 
                "Error variable de texto en:" + "\n" +
                "-Edad" + "\n" +
                "-Años de Esxperiencia" + "\n" + 
                "-Horas trabajadas"+"\n" +
                "-Pago por hora"+"\n" +
                "Casillas vacias", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        numArchivotxt=0;
        return null; 
    }
}
    
    public void Guardado_Archivo(){
        numArchivotxt++;
        String contenido = Recibo_final();
        if(numError==0){
                String rutaArchivo="";
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setSelectedFile(new File("Recibo_de_"+Nombre.getText()+"_"+numArchivotxt+".txt"));
                fileChooser.setDialogTitle("Selecciona un fichero");
                int resultado = fileChooser.showSaveDialog(null);
                if (resultado == JFileChooser.APPROVE_OPTION){
                rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();
            }
        try{
            FileWriter archivoEscritura = new FileWriter(rutaArchivo);
            BufferedWriter bufferEscritura = new BufferedWriter(archivoEscritura);

            bufferEscritura.write(contenido);
            bufferEscritura.close();
            archivoEscritura.close();
            JOptionPane.showMessageDialog(this, "Recibo guardado");
            
        }catch (IOException e) {
            numArchivotxt=0;
            JOptionPane.showMessageDialog(this, "Error al crear el archivo", "Error",JOptionPane.ERROR_MESSAGE);//en caso de error al guardar
        } 
        }
 }
    public void Salida_sin_guardar(){
                  if(numArchivotxt==0){
            Object[] opciones = {"Si", "No"};
            int respuesta = JOptionPane.showOptionDialog(this,
            "Salir sin guardar?",
            "Pregunta",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]);
                 if (respuesta != 0){
                Guardado_Archivo();  
                }  
          }       
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recibo_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recibo_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recibo_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recibo_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recibo_Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Anos_exp;
    private javax.swing.JTextField Apellidos;
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JTextField DNI;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Edad;
    private javax.swing.JLabel Estudios;
    private javax.swing.JComboBox<String> Estudios1;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField H_trabajadas;
    private javax.swing.JButton Limpiar;
    private javax.swing.JComboBox<String> Meses;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Pago_hora;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Texto_Ubi;
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton procesar;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
